baseURL = "https://norfolkgolang.org"
languageCode = "en-us"
Title = "Norfolk Go Meetup"
publishDir = "https://github.com/norfolkgo/norfolkgo.github.io.git"

[params]
  aboutText = "About us blurb goes here"
